version: '3.8'

services:
  flask:
    build:
      context: ./flask
    container_name: flask
    ports:
      - "5050:5050"
    volumes:
      - ./flask:/app
      - ./spotify:/app/spotify
      - mixster_files:/data
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    environment:
      # Celery
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      # Spotify
      SPOTIFY_CALLBACK_URL: ${SPOTIFY_CALLBACK_URL}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}

      # MariaDB
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_HOST: mariadb

      TZ: ${TIMEZONE-CET}
      FONT_PATH: "/usr/share/fonts/truetype/msttcorefonts/Arial.TTF"
    networks:
      - backend
      - frontend

  celery:
    build:
      context: ./flask
    container_name: celery
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./flask:/app
      - ./spotify:/app/spotify
      - mixster_files:/data
    depends_on:
      redis:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      FONT_PATH: "/usr/share/fonts/truetype/msttcorefonts/Arial.TTF"
      TZ: ${TIMEZONE-CET}

      # MariaDB
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_HOST: mariadb
    healthcheck:
      test: [ "CMD", "celery", "-A", "app.celery_app", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - "6379:6379"
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql      # Persistent storage for the database
      - ./mixster.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"  # Expose port 3306 for database access
    networks:
      - backend

volumes:
  mariadb_data:
  mixster_files:

networks:
  backend:
    internal: false
  frontend:
    internal: false